package mybatis.dao;

import java.util.List;
import mybatis.model.Album;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    Album selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    List<Album> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ALBUM
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    int updateByPrimaryKey(Album record);


    int deleteFromOrderedAlbums(Integer id);
}