package mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
public class Album {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.NAME
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.PRICE
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    private String price;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ID
     *
     * @return the value of PUBLIC.ALBUM.ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ID
     *
     * @param id the value for PUBLIC.ALBUM.ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.NAME
     *
     * @return the value of PUBLIC.ALBUM.NAME
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.NAME
     *
     * @param name the value for PUBLIC.ALBUM.NAME
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.PRICE
     *
     * @return the value of PUBLIC.ALBUM.PRICE
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public String getPrice() {
        return price;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.PRICE
     *
     * @param price the value for PUBLIC.ALBUM.PRICE
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public void setPrice(String price) {
        this.price = price;
    }

    // Added manually
    private List<Song> songs = new ArrayList<>();
    private List<Myorder> orders = new ArrayList<>();

    public List<Song> getSongs() {
        return songs;
    }

    public void setSongs(List<Song> songs) {
        this.songs = songs;
    }

    public List<Myorder> getOrders() {
        return orders;
    }

    public void setOrders(List<Myorder> orders) {
        this.orders = orders;
    }
}