package mybatis.model;

import lombok.Getter;
import lombok.Setter;
import mybatis.model.Album;
@Getter
@Setter
public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.NAME
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    private Integer albumId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ID
     *
     * @return the value of PUBLIC.SONG.ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ID
     *
     * @param id the value for PUBLIC.SONG.ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.NAME
     *
     * @return the value of PUBLIC.SONG.NAME
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.NAME
     *
     * @param name the value for PUBLIC.SONG.NAME
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @return the value of PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SONG.ALBUM_ID
     *
     * @param albumId the value for PUBLIC.SONG.ALBUM_ID
     *
     * @mbg.generated Mon May 02 19:03:51 EEST 2022
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    private Album album;

    public Album getAlbum() {
        return album;
    }

    public void setAlbum(Album album) {
        this.album = album;
    }
}